### ISSUE TITLE
ModuleNotFoundError: No module named 'ctpn

### ISSUE THREAD

**Issue by justprophet** [IanByun/Text-Detection-Recognition#1]
Hi,

I downloaded the dataset and your repository. When I ran the command:
python eval_on_coco_text.py

it gives an error:
File "C:\Users\Proph3t\My Scripts\ctpn_crnn_pytorch.py", line 23, in <module>
    import ctpn.demo as ctpn
ModuleNotFoundError: No module named 'ctpn'

Please help.

**Comment by IanByun** [comment]
Hi
I am not sure about the source of your problem,
but I suspect it has to do with current working directory problem.
Check https://github.com/IanByun/Text-Detection-Recognition/blob/master/eval_on_coco_text.py#L10
Ucommenting L10 may solve your problem.

**Comment by justprophet** [comment]
Hi Ian,

Thanks a lot. I was able to solve this problem. But now I am stuck with this Bbox issue:
raceback (most recent call last):
  File "eval_on_coco_text.py", line 17, in <module>
    from ctpn_crnn_pytorch import *
  File "C:\Users\Proph3t\My Scripts\ctpn_crnn_pytorch.py", line 23, in <module>
    import ctpn.demo as ctpn
  File "C:\Users\Proph3t\My Scripts\text-detection-ctpn\ctpn\demo.py", line 8, in <module>
    from lib.networks.factory import get_network
  File "C:\Users\Proph3t\My Scripts\text-detection-ctpn\lib\__init__.py", line 1, in <module>
    from . import fast_rcnn
  File "C:\Users\Proph3t\My Scripts\text-detection-ctpn\lib\fast_rcnn\__init__.py", line 2, in <module>
    from . import train
  File "C:\Users\Proph3t\My Scripts\text-detection-ctpn\lib\fast_rcnn\train.py", line 5, in <module>
    from ..roi_data_layer.layer import RoIDataLayer
  File "C:\Users\Proph3t\My Scripts\text-detection-ctpn\lib\roi_data_layer\__init__.py", line 1, in <module>
    from . import roidb
  File "C:\Users\Proph3t\My Scripts\text-detection-ctpn\lib\roi_data_layer\roidb.py", line 5, in <module>
    from lib.utils.bbox import bbox_overlaps
  File "C:\Users\Proph3t\My Scripts\text-detection-ctpn\lib\utils\__init__.py", line 4, in <module>
    from . import bbox
ImportError: cannot import name 'bbox' from 'lib.utils' (C:\Users\Proph3t\My Scripts\text-detection-ctpn\lib\utils\__init__.py)


Do I have to install Bbox or do I have to run the text detection code manually before and train that data before running text recognition?
Please help me out.

**Comment by IanByun** [comment]
I think you missed the ctpn set up instruction at
https://github.com/IanByun/text-detection-ctpn/tree/af07bd293ab3fec49da48d06113831ee655cbc65#setup.

The bbox util is written in cython, hence need to be compiled before hand.

**Comment by justprophet** [comment]
Thanks a lot. Sorry for troubling you again. I ran it and it asked me that some path is not set. Do we have to setup CUDA?
(base) C:\Users\Proph3t\My Scripts\text-detection-ctpn\lib\utils>python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 29, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDA_PATH

please help me out. 
Thanks a lots so far.

**Comment by IanByun** [comment]
All deep learning libraries rely on CUDA, so yes, you should setup envrionment variables related to CUDA and cuDNN.
Just google how to install Tensorflow and you will find how to setup CUDA materials.

Alternatively, use Anaconda.
Its management goes beyond what pip could offer, including CUDA path issues.

**Comment by justprophet** [comment]
I am running the scripts using Anaconda. That's why I thought I don't need to rely on Cuda
Is there a hard-Coded path that I need to set ?

**Comment by IanByun** [comment]
FYI, I am not the original author of CTPN, https://github.com/IanByun/text-detection-ctpn/tree/master/lib/utils.
If you look into it, you will notice there is nms_kernel.cu, which is the CUDA kernal.
It seems bbox utils also compile a cuda source, so NVCC path should be defined.

At the time I was writing this repo, I manually setup CUDA path, all was fine with me.

**Comment by IanByun** [comment]
https://github.com/omnia-md/conda-recipes/issues/813#issuecomment-450962940
Seems you still have to manually install CUDA, in order to use nvcc command.
Hope it helps.

**Comment by justprophet** [comment]
Ohkay. Thanks a lot for quick responses. 
I will look into it,
